Garant/Models/Finance.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Garant.Models
{
    public class Finance
    {
        public int Id { get; set; }
        public int NumberPhone { get; set; }
        public int Summa { get; set; }
        public DateTime DataCreated { get; set; }
        public string Status { get; set; }
        public string AuthorId { get; set; }
        public string AuthorName { get; set; }
    }
}

Garant/Controllers/FinanceController.cs
using Garant.Models;
using Garant.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Garant.Controllers
{
    public class FinanceController : Controller
    {
        private readonly ISqlBaseRepository _db;
        User user { get; set; }

        public FinanceController(ISqlBaseRepository db)
        {
            _db = db;
        }
        [HttpGet]
        public IActionResult AddMoney()
        {
            return View();
        }
        [HttpPost]
        public IActionResult AddMoney(int entersumma)
        {
            if (entersumma < 100000 && entersumma > 0)
            {
                _db.AddMoneyToUser(User.Identity.Name, entersumma);
                return Redirect("/Home/DetailUser");
            }
            else return Redirect("/Home/Index");
        }

        [HttpGet]
        public IActionResult TakeAwayMoney()
        {
            return View();
        }
        [HttpPost]
        public IActionResult TakeAwayMoney(int numberphone, int discardsumma)
        {
            user = _db.GetUserByLogin(User.Identity.Name);
            if(discardsumma <= user.QurencyBallance)
            {
                Finance finance = new Finance()
                {
                    NumberPhone = numberphone,
                    Summa = discardsumma,
                    Status = "В ожидании",
                    DataCreated = DateTime.Now,
                    AuthorId = user.Id,
                    AuthorName = user.UserName
                };
                _db.AddRequestFinance(finance);
                _db.TakeAwayMoneyForUser(User.Identity.Name, discardsumma);
            }
            return Redirect("/Home/DetailUser");
        }
    }
}

Garant/Views/Finance/AddMoney.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@using Microsoft.AspNetCore.Identity
@model Garant.Models.Deal;
<br />
<br />
<br />
<br />
<br />
<br />

<div class="col-md-12 order-md-1">
    <h4 class="mb-3 ml-4  ">Пополнение счета<br></h4>
    <form method="post" asp-controller="Finance" asp-action="AddMoney">
        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="firstName">Введите сумму пополнения</label>
                <input name="entersumma" type="number" class="form-control" placeholder="Сумма пополнения" value="" required>
            </div>
        </div>
        <hr class="mb-4">
        <button class=" button btn  btn-lg btn-block" type="submit">Пополнить счет</button>
    </form>
</div>


<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

Garant/Views/Finance/TakeAwayMoney.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}


@using Microsoft.AspNetCore.Identity
@model Garant.Models.Deal;
<br />
<br />
<br />
<br />
<br />
<br />

<div class="col-md-12 order-md-1">
    <h4 class="mb-3 ml-4  ">Вывод средств<br></h4>
    <form method="post" asp-controller="Finance" asp-action="TakeAwayMoney">
        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="firstName">Введите сумму вывода</label>
                <input name="discardsumma" type="number" class="form-control" placeholder="Сумма вывода" value="" required>
                <label for="firstName">Введите номер телефона</label>
                <input name="numberphone" type="number" class="form-control" placeholder="Номер телефона" value="" required>
            </div>
        </div>
        <hr class="mb-4">
        <button class=" button btn  btn-lg btn-block" type="submit">Вывести средства</button>
    </form>
</div>


<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />