Garant/Models/ChangePasswordViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Garant.Models
{
    public class ChangePasswordViewModel
    {
        public string Id { get; set; }
        public string Email { get; set; }
        public string NewPassword { get; set; }
        public string OldPassword { get; set; }
    }
}

Garant/Models/CommentsViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.EntityFrameworkCore;

namespace Garant.Models
{
    public class CommentsViewModel
    {
        public int ID { get; set; }
        public string Name { get; set; }
        public string  Surname { get; set; }
        public string Login { get; set; }   
        public string Email { get; set; }
        public string  Message { get; set; }
        public DateTime DataCreated { get; set; }

    }
}

Garant/Models/Deal.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Garant.Models
{
    public class Deal
    {

        public int Id { get; set; }
        public string NameDeal { get; set; }
        public string Explanation { get; set; }
        public string IdAuthor { get; set; }
        public string IdExecutor { get; set; }
        public DateTime DataCreated { get; set; }
        public DateTime DataFinish { get; set; }
        public int QurencySumma { get; set; }
        public bool AcceptForAuthor { get; set; }
        public bool AcceptForExucator { get; set; }
        public bool FinishAcceptForAuthor { get; set; }
        public bool FinishAcceptForExecutor { get; set; }
        public int DialogID { get; set; }
        public string Status { get; set; }
        [NotMapped]
        public string ReturnUrl { get; set; }
        [NotMapped]
        public string LoginForExucator { get; set; }
        [NotMapped]
        public int DayForFinish { get; set; }
    }
}

Garant/Controllers/DealsController.cs
using Garant.Models;
using Garant.Services;
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Garant.Controllers
{
    public class DealsController : Controller
    {
        private readonly ISqlBaseRepository _db;

        public DealsController(ISqlBaseRepository db)
        {
            _db = db;
        }
        public User author { get; set; }
        public User executor { get; set; }
        public Deal qdeal { get; set; }
        public int QurencyDealID { get; set; }

        [HttpGet]
        public IActionResult CreateDeal()
        {
            QurencyDealID = _db.GetUserQurencyDeal(User.Identity.Name);
            ViewBag.IdDealUser = QurencyDealID;
            return View();
        }
        [HttpPost]
        public IActionResult CreateDeal(Deal dealmodel)
        {
            User author = _db.GetUserByLogin(User.Identity.Name);
            User executor = _db.GetUserByLogin(dealmodel.LoginForExucator);
            if(executor != null)
            {
                if (author != null)
                {
                    if(author.QurencyBallance >= dealmodel.QurencySumma)
                    {
                        if(author.Active == false && executor.Active == false)
                        {
                            var deal = _db.AddDeal(dealmodel.NameDeal, dealmodel.Explanation, executor.Id, dealmodel.QurencySumma, dealmodel.DayForFinish, author.Id);
                            _db.ChangeStatusForParticipantsDeal(executor.Id, author.Id, _db.SearchDeals(author.Id));
                            return Redirect("/Deals/GarantDealProcess");
                        }
                    }
                }
            }
            return Redirect("/Deals/ErrorPageDeals");
        }
        [HttpGet]
        public IActionResult GarantDealProcess()
        {
            QurencyDealID = _db.GetUserQurencyDeal(User.Identity.Name);
            if(QurencyDealID != 0)
            {
                ViewBag.IdDealUser = QurencyDealID;
                ViewBag.DealInfo = _db.GetDealInfo(QurencyDealID);
                qdeal = _db.GetDealInfo(QurencyDealID);
                author = _db.GetUserByID(ViewBag.DealInfo.IdAuthor);
                executor = _db.GetUserByID(ViewBag.DealInfo.IdExecutor);
                ViewBag.QDeal = qdeal;
                ViewBag.Author = author;
                ViewBag.Executor = executor;
                ViewBag.DialogID = qdeal.DialogID;
                if (User.Identity.IsAuthenticated)
                {
                    if (author.UserName == User.Identity.Name || executor.UserName == User.Identity.Name)
                    {
                        return View();
                    }
                    return Redirect("/Home/Index");
                }
                else return Redirect("/Account/Login");
            }
            else return Redirect("/Home/Index");
        }
        public IActionResult Chat()
        {
            return View();
        }
        public IActionResult AcceptDealByExecutor() //Подтверждение заказа от исполнителя
        {
            QurencyDealID = _db.GetUserQurencyDeal(User.Identity.Name);
            if (QurencyDealID != 0)
            {
                qdeal = _db.GetDealInfo(QurencyDealID);
                author = _db.GetUserByID(qdeal.IdAuthor);
                if (qdeal.Status == "В ожидании подтверждения")
                {
                    qdeal.AcceptForExucator = true;
                    _db.TakeAwayMoneyForUser(author.UserName, qdeal.QurencySumma);
                    qdeal.Status = "В выполнении";
                    _db.SaveUserChanges(author);
                    _db.SaveDealChanges(qdeal);
                }
            }
            return Redirect("/Deals/GarantDealProcess");
        }
        public IActionResult CompleateDeal()
        {
            QurencyDealID = _db.GetUserQurencyDeal(User.Identity.Name);
            if (QurencyDealID != 0)
            {
                qdeal = _db.GetDealInfo(QurencyDealID);
                author = _db.GetUserByID(qdeal.IdAuthor);
                executor = _db.GetUserByID(qdeal.IdExecutor);
                if(qdeal.Status == "В выполнении")
                {
                    executor.QurencyBallance += qdeal.QurencySumma;
                    executor.Active = false;
                    author.Active = false;
                    executor.QurencyDeals = 0;
                    author.QurencyDeals = 0;
                    qdeal.Status = "Завершена";
                    qdeal.QurencySumma = 0;
                    qdeal.FinishAcceptForAuthor = true;
                    qdeal.FinishAcceptForExecutor = true;
                    _db.SaveDealChanges(qdeal);
                    _db.SaveUserChanges(author);
                    _db.SaveUserChanges(executor);
                }
            }
            return Redirect("/Deals/GarantDealProcess");
        }
        public IActionResult CancelDeal()
        {
            QurencyDealID = _db.GetUserQurencyDeal(User.Identity.Name);
            if (QurencyDealID != 0)
            {
                qdeal = _db.GetDealInfo(QurencyDealID);
                author = _db.GetUserByID(qdeal.IdAuthor);
                executor = _db.GetUserByID(qdeal.IdExecutor);
                if(qdeal.Status != "Завершена" && qdeal.Status != "Отменена")
                {
                    if(qdeal.Status == "В выполнении") author.QurencyBallance += qdeal.QurencySumma;
                    executor.Active = false;
                    author.Active = false;
                    executor.QurencyDeals = 0;
                    author.QurencyDeals = 0;
                    qdeal.Status = "Отменена";
                    qdeal.QurencySumma = 0;
                    qdeal.FinishAcceptForAuthor = true;
                    qdeal.FinishAcceptForExecutor = true;
                    _db.SaveDealChanges(qdeal);
                    _db.SaveUserChanges(author);
                    _db.SaveUserChanges(executor);
                }
            }
            return Redirect("/Deals/GarantDealProcess");
        }
        public IActionResult ErrorPageDeals()
        {
            return View();
        }
    }
}

Garant/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using Garant.Models;
using System.Net.Mail;
using Garant.Services;
using Microsoft.AspNetCore.Identity;

namespace Garant.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;
        private readonly Service service;
        private readonly ISqlBaseRepository _db;
        public int QurencyDealID { get; set; }
        public User UserVerifyAdmin { get; set; }
        UserManager<User> _userManager;
        public IEnumerable<CommentsViewModel> Comments { get; set; }
        public HomeController(ILogger<HomeController> logger, Service service, ISqlBaseRepository db, UserManager<User> userManager)
        {
            _userManager = userManager;
            _logger = logger;
            this.service = service;
            _db = db;
        }

        public IActionResult Index()
        {
            QurencyDealID = _db.GetUserQurencyDeal(User.Identity.Name);
            ViewBag.IdDealUser = QurencyDealID;
            UserVerifyAdmin = _db.GetUserByLogin(User.Identity.Name);
            ViewBag.UserVerefy = UserVerifyAdmin;
            return View();
        }
        public IActionResult DetailUser()
        {
            if (User.Identity.IsAuthenticated)
            {
                UserVerifyAdmin = _db.GetUserByLogin(User.Identity.Name);
                QurencyDealID = _db.GetUserQurencyDeal(User.Identity.Name);
                if (UserVerifyAdmin != null)
                {
                    ViewBag.UserVerefy = UserVerifyAdmin;
                    ViewBag.IdDealUser = QurencyDealID;
                    ViewBag.UserPayment = UserVerifyAdmin.PayMent;
                    return View();
                }
                else return Redirect("/Account/Login");
            }
            else return Redirect("/Account/Login");
        }
        [HttpGet]
        public IActionResult comments()
        {
            return View();
        }
        public IActionResult CommentIndex()
        {
            Comments = _db.GetComments();
            ViewBag.ListComment = Comments;
            return View();
        }
        [HttpPost]
        public IActionResult CreateComment(CommentsViewModel comment)
        {
            _db.AddComment(comment.Name, comment.Surname, comment.Login, comment.Email, comment.Message);
            return Redirect("CommentIndex");
        }
        public IActionResult ErrorFindOfPage()
        {
            QurencyDealID = _db.GetUserQurencyDeal(User.Identity.Name);
            ViewBag.IdDealUser = QurencyDealID;
            return View();
        }

        public IActionResult contact()
        {
            QurencyDealID = _db.GetUserQurencyDeal(User.Identity.Name);
            ViewBag.IdDealUser = QurencyDealID;
            return View();
        }

        public IActionResult help()
        {
            QurencyDealID = _db.GetUserQurencyDeal(User.Identity.Name);
            ViewBag.IdDealUser = QurencyDealID;
            return View();
        }
        public IActionResult join()
        {
            QurencyDealID = _db.GetUserQurencyDeal(User.Identity.Name);
            ViewBag.IdDealUser = QurencyDealID;
            return View();
        }

        public IActionResult static2()
        {
            QurencyDealID = _db.GetUserQurencyDeal(User.Identity.Name);
            ViewBag.IdDealUser = QurencyDealID;
            return View();
        }

        public IActionResult Login()
        {
            QurencyDealID = _db.GetUserQurencyDeal(User.Identity.Name);
            ViewBag.IdDealUser = QurencyDealID;
            return View(); 
        }
        public IActionResult staticpage()
        {
            QurencyDealID = _db.GetUserQurencyDeal(User.Identity.Name);
            ViewBag.IdDealUser = QurencyDealID;
            return View();
        }
        public IActionResult DisputeResolution()
        {
            QurencyDealID = _db.GetUserQurencyDeal(User.Identity.Name);
            ViewBag.IdDealUser = QurencyDealID;
            return View();
        }
        public IActionResult Deal()
        {
            QurencyDealID = _db.GetUserQurencyDeal(User.Identity.Name);
            ViewBag.IdDealUser = QurencyDealID;
            return View();
        }
        public async Task<IActionResult> ChangePassword(string id)
        {
            User user = await _userManager.FindByIdAsync(id);
            if (user == null)
            {
                return NotFound();
            }
            ChangePasswordViewModel model = new ChangePasswordViewModel { Id = user.Id, Email = user.Email };
            return View(model);
        }

        [HttpPost]
        public async Task<IActionResult> ChangePassword(ChangePasswordViewModel model)
        {
            if (ModelState.IsValid)
            {
                User user = await _userManager.FindByIdAsync(model.Id);
                if (user != null)
                {
                    IdentityResult result =
                        await _userManager.ChangePasswordAsync(user, model.OldPassword, model.NewPassword);
                    if (result.Succeeded)
                    {
                        return RedirectToAction("Index");
                    }
                    else
                    {
                        foreach (var error in result.Errors)
                        {
                            ModelState.AddModelError(string.Empty, error.Description);
                        }
                    }
                }
                else
                {
                    ModelState.AddModelError(string.Empty, "Пользователь не найден");
                }
            }
            return View(model);
        }
        [HttpPost]
        public IActionResult contact(Email em)
        {
            string name = em.Name;
            string subject = em.Subject;
            string body = em.Body;
            MailMessage mm = new MailMessage();
            mm.To.Add("iprusevich@gmail.com");
            mm.Subject = subject;
            mm.Body = name + " "+ body;
            mm.From = new MailAddress("d1msogarant@gmail.com");
            mm.IsBodyHtml = false;
            SmtpClient smtp = new SmtpClient("smtp.gmail.com");
            smtp.Port = 587;
            smtp.UseDefaultCredentials = true;
            smtp.EnableSsl = true;
            smtp.Credentials = new System.Net.NetworkCredential("iwannaparadise@gmail.com", "");
            smtp.Send(mm); 
            return View();
        }
        public IActionResult SendEmail()
        {
            service.SendEmail();
            return RedirectToAction("Index");
        }
        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            QurencyDealID = _db.GetUserQurencyDeal(User.Identity.Name);
            ViewBag.IdDealUser = QurencyDealID;
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Garant/Views/Home/ChangePassword.cshtml
@model Garant.Models.ChangePasswordViewModel
@{
    ViewData["Title"] = "ChangePassword";
    Layout = "_Layout";
}
    <div class="container text-center text-gradient mt-5 mb-1">
        <h1>Изменение пароля для пользователя @Model.Email</h1>
    </div>
<form asp-action="ChangePassword" asp-controller="Home">
    <div asp-validation-summary="All" class="text-danger"></div>

    <input type="hidden" asp-for="Id" />
    <input type="hidden" asp-for="Email" />
    <div class="form-group">
        <label asp-for="OldPassword" class="control-label">Старый пароль</label>
        <input type="text" asp-for="OldPassword" class="form-control" />
    </div>
    <div class="form-group">
        <label asp-for="NewPassword" class="control-label">Новый пароль</label>
        <input type="text" asp-for="NewPassword" class="form-control" />
    </div>
    <div class="form-group">
        <input type="submit" value="Сохранить" class="btn btn-default" />
    </div>
</form>
<br /><br /><br /><br /><br />

Garant/Views/Home/CommentIndex.cshtml
@model IEnumerable<Garant.Models.CommentsViewModel>
@{
    ViewBag.Title = "Все комментарии";
}


<div class="container text-center text-gradient mt-5 mb-1">
    <h1>Все отзывы</h1>
    <hr>
</div>
<section>
    <div class="container">
        <div class="row">

            @foreach (var item in ViewBag.ListComment)
            {
                <div class="col-sm-5 col-md-12 col-12 pb-4">
                    <div class="comment mt-4 text-justify float-left">
                        <img src="https://i.imgur.com/CFpa3nK.jpg" alt="" class="rounded-circle" width="40" height="40">
                        <h4>@item.Name </h4> <h4>@item.Surname</h4> <span>- @item.DataCreated.ToString("d")</span> <br>
                        <p>@item.Message</p>
                    </div>
                </div>

            }
            <a asp-action="comments" asp-controller="Home" class="col-md-3  button btn  btn-lg btn-block" type="submit">Добавить комментарий</a>
        </div>
    </div>
</section>


<style>
    #profile {
        background-color: unset
    }

    #post {
        margin: 10px;
        padding: 6px;
        padding-top: 2px;
        padding-bottom: 2px;
        text-align: center;
        background-color: #ecb21f;
        border-color: #a88734 #9c7e31 #846a29;
        color: black;
        border-width: 1px;
        border-style: solid;
        border-radius: 13px;
        width: 50%
    }


    #profile {
        text-decoration: none;
        color: rgb(224, 219, 219);
        background-color: black
    }

    .comments {
        margin-top: 5%;
        margin-left: 20px
    }


    .comment {
        border: 1px solid #6c757d;
        float: left;
        border-radius: 5px;
        padding-left: 40px;
        padding-right: 30px;
        padding-top: 10px
    }

        .comment h4,
        .comment span,
        .darker h4,
        .darker span {
            display: inline
        }

        .comment p,
        .comment span,
        .darker p,
        .darker span {
            color: rgb(184, 183, 183)
        }

    h1,
    h4 {
        font-weight: bold
    }

    label {
        color: rgb(212, 208, 208)
    }

    #align-form {
        margin-top: 20px
    }

 

    #checkbx {
        background-color: black
    }

    #darker img {
        margin-right: 15px;
        position: static
    }


</style>

Garant/Views/Home/Deal.cshtml
@using Microsoft.AspNetCore.Identity

<br />
<br />
<br />
<br />
<br />
<br />

<div class="col-md-12 order-md-1">
    <h4 class="mb-3 ml-4  ">Сделка<br></h4>
    <form class="needs-validation" novalidate>
        <div class="row">
            <div class="col-md-6 mb-3">
                <label for="firstName">Имя пользователя</label>
                <input type="text" class="form-control" id="firstName" placeholder="" value="" required>
                <div class="invalid-feedback">
                    Valid first name is required.
                </div>
            </div>
        </div>

        <div class="mb-3">
            <label for="email">Email <span class="text-muted">(Необязательно)</span></label>
            <input type="email" class="form-control" id="email" placeholder="пример@tut.by">
            <div class="invalid-feedback">
                Please enter a valid email address for shipping updates.
            </div>
        </div>
        <div class="mb-3">
            <label for="lastName">Сообщение</label>
            <input type="text" class="form-control" id="Message" placeholder="" value="" required>
            <hr class="mb-4">
            <button class=" button btn  btn-lg btn-block" type="submit">Отправить</button>
        </div>
    </form>
</div>

<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />
<br />

Garant/Views/Home/DetailUser.cshtml
@{ Layout = "_Layout"; }

<div class="container text-center text-gradient mt-5 mb-1">
    <h1>Личный кабинет</h1>
    <hr>
</div>

<span class="border border-primary">
    <div class="col-md-12 order-md-1">
        <form class="needs-validation" asp-controller="Home" asp-action="DetailUser" novalidate>
            <div class="mb-3">
                <label for="NameOfDeal">Имя аккаунта:<h4>@ViewBag.UserVerefy.UserName</h4> </label>
            </div>
            <div class="mb-3">
                <label for="Status">Балланс: <h4>@ViewBag.UserVerefy.QurencyBallance</h4></label>
            </div>

            <div class="mb-3">
                <label for="NameOfCreator">Электронные деньги: @ViewBag.UserPayment</label>
            </div>
            @if (ViewBag.IdDealUser != 0)
            {
            <div class="mb-3">
                <label for="DateOfCreate">Текущий статус: <h4>@ViewBag.UserVerefy.QurencyDeals</h4> </label>
            </div> }
            else
            {
            <div class="mb-3">
                <label for="DateOfCreate">Текущий статус:<h4> Не занят</h4></label>
            </div>}

            <div class="mb-3">
                <label for="DateOfCreate">Кошельки: <h4>@ViewBag.UserVerefy.QurencyBallance</h4></label>
            </div>
            <div class="mb-3">
                <label for="DateOfCreate">Данные кошелька <h4>@ViewBag.UserVerefy.QurencyBallance</h4></label>
            </div>

            <div class="row">
                <div class="mb-3">
                </div>
                <br />
            </div>

            <div class="buttonrigth">
                <a class="button btn btn-lg btn-block text-center" asp-controller="Finance" asp-action="AddMoney">Добавить средства</a>
                <a class=" button btn  btn-lg btn-block text-center" asp-controller="Finance" asp-action="TakeAwayMoney">Вывод средств</a>
                <a class="button btn btn-lg btn-block text-center" asp-controller="Home" asp-action="ChangePassword" asp-route-id="@ViewBag.UserVerefy.Id">Изменить пароль</a>

            </div>
        </form>
    </div>
</span>

<style>
    .display-grid {
        display: grid;
    }

    .buttonrigth {
        position: absolute;
        top: 0;
        right: 0;
    }

    .text-bold {
        font-family: 'Montserrat', sans-serif;
        color: #808080;
    }

    h4 {
        display: inline;
        font-weight: bold;
    }

    h4, h4 {
        font-size: 17px;
    }
</style>

Garant/Views/Home/DisputeResolution.cshtml
@{ Layout = "_Layout"; }

<div class="container text-center text-gradient mt-5 mb-1">
    <h1>Арбитраж D1msolino</h1>
    <hr>
</div>


<main role="main">
    <div class="container">
        <p>
            Арбитраж несет материальную ответственность за разрешение споров в системе D1msoGarant в размере, двукратно превышающим сумму сделки. Таким образом, в случае какой-либо ошибки в разрешении спора, сервис обязуется компенсировать все убытки (как прямые, так и косвенные).
        </p>

            <br>
            <br>
            <h1 class="text-center">
                В каком случае требуется участие арбитража?
            </h1>

            <p>
                Участие арбитража может потребоваться в том случае, если участники сделки не могут разрешить спор самостоятельно, при этом баланс сделки должен быть отличен от нуля. В компетенцию арбитража входит вынесение решения о распределении средств сделки между её участниками.
            </p>
            <h1 class="text-center">
                Каким образом обратиться в арбитраж?

            </h1>

            <p>
                Любой из участников сделки может направить соответствующее обращение консультанту в правом нижнем углу сайта либо на почту d1msolino@gmail.com. Разбирательство начинается в чате сделки в течение 5 рабочих дней с момента обращения.
            </p>
        </div>
</main>

Garant/Views/Home/ErrorFindOfPage.cshtml
@{
    Layout = "_Layout";
}


    <div id="notfound">
        <div class="notfound">
            <div class="notfound-404">
                <h1>404</h1>
                <hr>
            </div>
            <h2>Страница не найдена</h2>
            <p>Страница которую вы ищите может быть удалена.</p>

        </div>
    </div>

Garant/Views/Home/Index.cshtml
@{
    Layout = "_Layout";}

@using Microsoft.AspNetCore.Identity;


<div class="container-fluid text-center   ">


    <div class="cont ">
        <div class="row">
            <div class="mx-auto col-md-7 col-sm-12 text-gradient animated fadeInUp">
                <h1>
                    Мы гарантируем вам 100% <br> сделку с минимальной <br> комиссией
                </h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12">
                @if (User.Identity.IsAuthenticated)
                {
                    <button class="button ">
                        <a class="buttons buttons-text" asp-action="CreateDeal" asp-controller="Deals">Создать сделку</a>
                    </button>
                }
                else
                {
                    <button class="button ">
                        <a class="buttons buttons-text" asp-action="Register" asp-controller="Account">Создать сделку</a>
                    </button>
                }
            </div>
        </div>

    </div>
    <div class="container text-center ">
        <div class="row">
            <div class="col-md-12 col-sm-12 mt-4 animated   ">
                <h1>
                    Что такое безопасная сделка?
                </h1>
            </div>
        </div>
        <div class="row">
            <div class="col-md-12 col-sm-12 text mt-5 mb-5 animated ">
                <p>
                    Безопасная сделка – сервис защиты покупателя и продавца в интернете.
                    Безопасная сделка гарантирует 100% предоплату, которая хранится на счёте
                    гаранта ,
                    пока продавец не выполнит все свои обязательства, а покупатель не
                    получит товар или услугу.

                </p>
            </div>
        </div>
    </div>
    <hr>

    <div class="container text-center mt-5">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <h1>
                    Преимущества GarantD1mso
                </h1>
            </div>
        </div>
        <div class="row mt-5">
            <div class="col-md-4 col-sm-12">
                <img src="img/quality 1.png" alt="Качество">
                <p class="text mt-4">Качественно</p>
            </div>
            <div class="col-md-4 col-sm-12">
                <img src="img/surface1.png" alt="Безопасно">
                <p class="text mt-4">Безопасно</p>
            </div>
            <div class="col-md-4 col-sm-12">
                <img src="img/Анонимно.png" alt="Анонимно">
                <p class="text mt-4"> Анонимно</p>
            </div>
        </div>
    </div>
    <hr>


    <div class="container text-center mt-5">
        <div class="row">
            <div class="col-md-12 col-sm-12">
                <h1>
                    Сколько стоит безопасная сделка?
                </h1>
            </div>
        </div>
        <div class="row mt-1">
            <div class="col-md-6 col-sm-12 ">
                <p class="text mt-4">Сумма сделки</p>
                <input type="text" id="txtFirst"> </br>
            </div>
            <div class="col-md-6 col-sm-12">
                <p class="text mt-4">Комиссия</p>
                <input type="text" id="txtResult">
            </div>
        </div>

        <div class="row">
            <div class="col-md-12 col-sm-12">
                
                <button class="button" id="btnOK">
                    <a class="buttons buttons-text">Рассчитать</a>
                </button>

            </div>
        </div>
    </div>
</div>


<hr>
<div class="container text-center mt-5">
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <h1>
                Как происходит безопасная сделка через гарант-сервис?
            </h1>
        </div>
    </div>
    <div class="row mt-5">
        <div class=" blockof mx-auto col-lg-2 col-md-5 col-sm-12">
            <img src="img/Как происходит сделка1.png" alt="Качество">
            <p class="text2 mt-4">Продавец и покупатель договорились о безопасной сделке</p>
        </div>
        <div class=" blockof mx-auto col-lg-2  col-md-5 col-sm-12">
            <img src="img/Как происходит сделка 2.png" alt="Безопасно">
            <p class="text2 mt-4">Покупатель переводит деньги на безопасный счет </p>
        </div>
        <div class=" blockof mx-auto col-lg-2 col-md-5 col-sm-12">
            <img src="img/Как происходит сделка3.png" alt="Анонимно">
            <p class="text2 mt-4"> Продавец осуществляет передачу товара или услуги покупателю</p>
        </div>
        <div class=" blockof mx-auto col-lg-2 col-md-5 col-sm-12">
            <img src="img/Как происходит сделка 3.png" alt="Анонимно">
            <p class="text2 mt-4">
                Покупатель принимает товар, проверяет его соответствие условиям
                сделки
            </p>
        </div>
        <div class=" blockof mx-auto col-lg-2 col-md-5 col-sm-12">
            <img src="img/Как происходит сделка 5.png" alt="Анонимно">
            <p class="text2 mt-4">
                Сервис переводит деньги продавцу и завершает безопасную сделку
            </p>
        </div>
    </div>
</div>
<hr>
<div class="container text-center mt-2">
    <div class="row">
        <div class="col-md-12 col-sm-12">
            <h1>
                Наши группы
            </h1>
        </div>
    </div>
    <div class="row mt-5">
        <div class="col-lg-3 col-md-5 col-sm-6 mt-5">
            <p class="text mt-4">EnjoyMaloy</p>
        </div>
        <div class="col-lg-3 col-md-5 col-sm-6 ">
            <a href="https://vk.com/enjoymaloy" target="_blank">
                <img src="img/EnjoyMaloy.png"
                     alt="EnjoyMaloy">
            </a>
        </div>
        <div class="col-lg-3 col-md-5 col-sm-6 second__img">
            <a href="https://vk.com/d1msolinostat" target="_blank">
                <img src="img/D1mso.png"
                     alt="D1msolinostat">
            </a>
        </div>
        <div class="col-lg-3     col-md-5 col-sm-6 mt-5 ">
            <p class="text mt-4">D1msolinostat</p>
        </div>
    </div>
</div>